experimental_monorepo_root = true

[tools]
# Environments
node = 'latest'
'github:nubjs/nub' = { version = 'latest', postinstall = 'nub pm pin' }
# Linters & Formatters
hk = 'latest'
stylua = 'latest'
pkl = 'latest'

[deps.nub]
description = 'Automatically install Node.js dependencies via nub.'
sources = ['package.json', 'nub.lock']
outputs = ['node_modules/']
run = 'nub install'
auto = true

[monorepo]
config_roots = ["docs/", "packages/*", "playground/"]

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.dev]
description = "Run the development build with hot reloading."
run = { task = "//packages/...:dev" }

[tasks.build]
description = "Run the production build."
run = { task = "//packages/...:build" }

[tasks.start]
description = "Run the source code."
run = { task = "//packages/pkg-placeholder:start" }

[tasks.docs]
description = "Run the docs in the specified mode."
usage = '''
arg "<mode>" help="The mode to run the docs in. Can be one of: dev, build, start."
'''
run = { task = "//docs:{{usage.mode}}" }

[tasks.play]
description = "Run the playground."
run = { task = "//playground:play" }

[tasks.check]
description = 'Run all checks.'
depends = "build"
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk check {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''

[tasks.fix]
description = 'Fix all check issues.'
depends = "build"
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk fix {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''

[tasks.test]
description = "Run tests."
depends = "build"
usage = '''
flag "-w --watch" help="Watch files for changes and rerun tests"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
vitest {{ '' if usage.watch else 'run' }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''

[tasks.prerelease]
description = 'Prepare for release.'
# All tasks in parallel.
run = { tasks = [":check", ":test"] }

[tasks.release]
description = 'Bump the version and push new version of all packages with a Git tag.'
depends = ":prerelease"
run = "bumpp --recursive"
raw = true

[tasks.publish]
description = 'Publish the package.'
run = "nub publish --recursive --provenance"

[tasks.publish-commit]
run = "pkg-pr-new publish packages/*"
